apiVersion: v1
kind: ConfigMap
metadata:
  name: authorative-pdns-conf-cm
data:
  pdns.conf: |
    local-address=0.0.0.0,::
    local-port=8053
    launch=gsqlite3
    gsqlite3-dnssec
    gsqlite3-database=/var/lib/powerdns/pdns.sqlite3
    #include-dir=/etc/powerdns/pdns.d  
