{{- if .Values.service.web.api.apiKey }}
apiVersion: v1
type: Opaque
data:
  {{ .Values.service.web.api.secretKey | default "apikey" }}: "{{ .Values.service.web.api.apiKey | b64enc }}"
kind: Secret
metadata:
  name: {{ printf "%s-api" ( include "k8str-powerdns-chart.fullname" .) }}
  labels:
    {{- include "k8str-powerdns-chart.labels" . | nindent 4 }}
{{- end }}
