apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8str-powerdns-chart.fullname" . }}
  labels:
    {{- include "k8str-powerdns-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.publishDNS }}
    - port: {{ .Values.service.dns.port }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.service.dns.port }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp   
    {{- end }}
  selector:
    {{- include "k8str-powerdns-chart.selectorLabels" . | nindent 4 }}
